/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 */

#ifndef	_Constraint_H_
#define	_Constraint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum operator_c {
	operator_c_eq	= 0,
	operator_c_ne	= 1,
	operator_c_lt	= 2,
	operator_c_le	= 3,
	operator_c_gt	= 4,
	operator_c_ge	= 5
} e_operator_c;

/* Constraint */
typedef struct Constraint {
	long	 operator_c;
	Value_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Constraint_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_operator_c_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Constraint;

#ifdef __cplusplus
}
#endif

#endif	/* _Constraint_H_ */
#include <asn_internal.h>
