/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Constraint_H_
#define	_Constraint_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Constraint__operator {
	Constraint__operator_eq	= 0,
	Constraint__operator_ne	= 1,
	Constraint__operator_lt	= 2,
	Constraint__operator_le	= 3,
	Constraint__operator_gt	= 4,
	Constraint__operator_ge	= 5
} e_Constraint__operator;

/* Constraint */
typedef struct Constraint {
	long	 operator;
	Value_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Constraint_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_operator_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Constraint;

#ifdef __cplusplus
}
#endif

#endif	/* _Constraint_H_ */
#include <asn_internal.h>
