/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Expression_H_
#define	_Expression_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Expression__operator_e {
	Expression__operator_e_and	= 0,
	Expression__operator_e_or	= 1
} e_Expression__operator_e;

/* Forward declarations */
struct Query;

/* Expression */
typedef struct Expression {
	long	 operator_e;
	struct Query	*left;
	struct Query	*right;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Expression_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_operator_e_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Expression;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Query.h"

#endif	/* _Expression_H_ */
#include <asn_internal.h>
