/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_FormatResponse_H_
#define	_FormatResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Format.h"
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FormatResponse */
typedef struct FormatResponse {
	long	 rid;
	Format_t	 assessment_id;
	IA5String_t	 assessment_def;
	Format_t	 trust_id;
	IA5String_t	 trust_def;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FormatResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FormatResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _FormatResponse_H_ */
#include <asn_internal.h>
