/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_FormatRequest_H_
#define	_FormatRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FormatRequest */
typedef long	 FormatRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FormatRequest;
asn_struct_free_f FormatRequest_free;
asn_struct_print_f FormatRequest_print;
asn_constr_check_f FormatRequest_constraint;
ber_type_decoder_f FormatRequest_decode_ber;
der_type_encoder_f FormatRequest_encode_der;
xer_type_decoder_f FormatRequest_decode_xer;
xer_type_encoder_f FormatRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FormatRequest_H_ */
#include <asn_internal.h>
