/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Message_H_
#define	_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Entity.h"
#include "DataRequest.h"
#include "DataResponse.h"
#include "FormatRequest.h"
#include "FormatResponse.h"
#include "Fault.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Message__payload_PR {
	Message__payload_PR_NOTHING,	/* No components present */
	Message__payload_PR_data_request,
	Message__payload_PR_data_response,
	Message__payload_PR_format_request,
	Message__payload_PR_format_response,
	Message__payload_PR_fault
} Message__payload_PR;

/* Message */
typedef struct Message {
	long	 version;
	Entity_t	 caller;
	Entity_t	 callee;
	struct Message__payload {
		Message__payload_PR present;
		union Message__payload_u {
			DataRequest_t	 data_request;
			DataResponse_t	 data_response;
			FormatRequest_t	 format_request;
			FormatResponse_t	 format_response;
			Fault_t	 fault;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} payload;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _Message_H_ */
#include <asn_internal.h>
