/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names`
 */

#include "Message.h"

static asn_TYPE_member_t asn_MBR_payload_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Message__payload, choice.data_request),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		0,
		&asn_DEF_DataRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Message__payload, choice.data_response),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		0,
		&asn_DEF_DataResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data-response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Message__payload, choice.format_request),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		0,
		&asn_DEF_FormatRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"format-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Message__payload, choice.format_response),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		0,
		&asn_DEF_FormatResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"format-response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Message__payload, choice.fault),
		(ASN_TAG_CLASS_APPLICATION | (7 << 2)),
		0,
		&asn_DEF_Fault,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fault"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_payload_tag2el_3[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 2, 0, 0 }, /* format-request */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 3, 0, 0 }, /* format-response */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 0, 0, 0 }, /* data-request */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 1, 0, 0 }, /* data-response */
    { (ASN_TAG_CLASS_APPLICATION | (7 << 2)), 4, 0, 0 } /* fault */
};
static asn_CHOICE_specifics_t asn_SPC_payload_specs_3 = {
	sizeof(struct Message__payload),
	offsetof(struct Message__payload, _asn_ctx),
	offsetof(struct Message__payload, present),
	sizeof(((struct Message__payload *)0)->present),
	asn_MAP_payload_tag2el_3,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_payload_3 = {
	"payload",
	"payload",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_payload_3,
	5,	/* Elements count */
	&asn_SPC_payload_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Message_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Message, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Message, payload),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_payload_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"payload"
		},
};
static const ber_tlv_tag_t asn_DEF_Message_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Message_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* format-request */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* format-response */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 }, /* data-request */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 1, 0, 0 }, /* data-response */
    { (ASN_TAG_CLASS_APPLICATION | (7 << 2)), 1, 0, 0 } /* fault */
};
static asn_SEQUENCE_specifics_t asn_SPC_Message_specs_1 = {
	sizeof(struct Message),
	offsetof(struct Message, _asn_ctx),
	asn_MAP_Message_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Message = {
	"Message",
	"Message",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Message_tags_1,
	sizeof(asn_DEF_Message_tags_1)
		/sizeof(asn_DEF_Message_tags_1[0]), /* 1 */
	asn_DEF_Message_tags_1,	/* Same as above */
	sizeof(asn_DEF_Message_tags_1)
		/sizeof(asn_DEF_Message_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Message_1,
	2,	/* Elements count */
	&asn_SPC_Message_specs_1	/* Additional specs */
};

