/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Formats"
 * 	found in "../asn1-trustmessages/formats.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_SL_H_
#define	_SL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL */
typedef struct SL {
	double	 b;
	double	 d;
	double	 u;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_H_ */
#include <asn_internal.h>
