/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Messages"
 * 	found in "../asn1-trustmessages/messages.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "Value.h"

static asn_per_constraints_t asn_PER_type_Value_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Value_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Value, choice.source),
		(ASN_TAG_CLASS_APPLICATION | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Entity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"source"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Value, choice.target),
		(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Entity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"target"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Value, choice.date),
		(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BinaryTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"date"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Value, choice.service),
		(ASN_TAG_CLASS_APPLICATION | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Service,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"service"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Value_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 0, 0, 0 }, /* source */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* target */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 2, 0, 0 }, /* date */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 3, 0, 0 } /* service */
};
static asn_CHOICE_specifics_t asn_SPC_Value_specs_1 = {
	sizeof(struct Value),
	offsetof(struct Value, _asn_ctx),
	offsetof(struct Value, present),
	sizeof(((struct Value *)0)->present),
	asn_MAP_Value_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Value = {
	"Value",
	"Value",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_Value_constr_1,
	asn_MBR_Value_1,
	4,	/* Elements count */
	&asn_SPC_Value_specs_1	/* Additional specs */
};

